set -x

mv run_nam_catchup_post_alaska_tm02_f00.sh run_nam_catchup_post_alaska_tm02_f00.sh
mv run_nam_catchup_post_alaska_tm02_f01.sh run_nam_catchup_post_alaska_tm02_f01.sh
mv run_nam_catchup_post_conus_tm02_f00.sh run_nam_catchup_post_conus_tm02_f00.sh
mv run_nam_catchup_post_conus_tm02_f01.sh run_nam_catchup_post_conus_tm02_f01.sh
mv run_nam_catchup_post_tm02_f00.sh run_nam_catchup_post_tm02_f00.sh
mv run_nam_catchup_post_tm02_f01.sh run_nam_catchup_post_tm02_f01.sh
mv run_nam_catchup_prdgen_alaska_tm02_f00.sh run_nam_catchup_prdgen_alaska_tm02_f00.sh
mv run_nam_catchup_prdgen_alaska_tm02_f01.sh run_nam_catchup_prdgen_alaska_tm02_f01.sh
mv run_nam_catchup_prdgen_conus_tm02_f00.sh run_nam_catchup_prdgen_conus_tm02_f00.sh
mv run_nam_catchup_prdgen_conus_tm02_f01.sh run_nam_catchup_prdgen_conus_tm02_f01.sh
mv run_nam_catchup_prdgen_tm02_f00.sh run_nam_catchup_prdgen_tm02_f00.sh
mv run_nam_catchup_prdgen_tm02_f01.sh run_nam_catchup_prdgen_tm02_f01.sh
