set -x

mv run_nam_catchup_post_alaska_tm06_f00.sh run_nam_catchup_post_alaska_tm01_f00.sh
mv run_nam_catchup_post_alaska_tm06_f01.sh run_nam_catchup_post_alaska_tm01_f01.sh
mv run_nam_catchup_post_conus_tm06_f00.sh run_nam_catchup_post_conus_tm01_f00.sh
mv run_nam_catchup_post_conus_tm06_f01.sh run_nam_catchup_post_conus_tm01_f01.sh
mv run_nam_catchup_post_tm06_f00.sh run_nam_catchup_post_tm01_f00.sh
mv run_nam_catchup_post_tm06_f01.sh run_nam_catchup_post_tm01_f01.sh
mv run_nam_catchup_prdgen_alaska_tm06_f00.sh run_nam_catchup_prdgen_alaska_tm01_f00.sh
mv run_nam_catchup_prdgen_alaska_tm06_f01.sh run_nam_catchup_prdgen_alaska_tm01_f01.sh
mv run_nam_catchup_prdgen_conus_tm06_f00.sh run_nam_catchup_prdgen_conus_tm01_f00.sh
mv run_nam_catchup_prdgen_conus_tm06_f01.sh run_nam_catchup_prdgen_conus_tm01_f01.sh
mv run_nam_catchup_prdgen_tm06_f00.sh run_nam_catchup_prdgen_tm01_f00.sh
mv run_nam_catchup_prdgen_tm06_f01.sh run_nam_catchup_prdgen_tm01_f01.sh
